version: "3.7"

services:
  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
    links:
      - db
  db:
    container_name: db
    image: mongo
    restart: always
    # volumes:
    #   - ./data:/data/db
    ports:
      - "27017:27017"
